### PR TITLE
CKEditor custom plugins loading fix (#196)

### LINKED ISSUE #196: CKEditor custom plugins are not being loaded
#### Sonata packages
SonataFormatterBundle 3.x-dev (3.0.1)
```bash
name     : sonata-project/formatter-bundle
descrip. : Symfony SonataFormatterBundle
keywords : CKEditor, formatter, markdown, markitup, sonata
versions : * 3.x-dev
```

## Subject

CKEditor custom plugins are not being loaded in the admin panel during rendering Formatter Block in Pages. I guess this happens because PluginManager is not being passed to the FormatterType constructor.

## Steps to reproduce

Try to use SonataFormatterBundle with SonataPageBundle and render sonata.formatter.block.formatter in the Composer (in the SonataPage context, not the package manager).

## Quick fix
I came up with a quick fix that requires modification of 3 files. I don't know if it is the best solution, but worked for me:

**sonata-project/formatter-bundle/Resources/config/form.xml after line 8**
Pass the PluginManager to the sonata.formatter.form.type.selector service:
```xml
[...]
    <argument type="service" id="ivory_ck_editor.config_manager"/>
    <argument type="service" id="ivory_ck_editor.plugin_manager"/>
[...]
```

**sonata-project/formatter-bundle/Resources/views/Form/formatter.html.twig after line 55**
Render plugins in the view:
```twig
[...]
case 'richhtml':
    {% for plugin_name, plugin in ckeditor_plugins %}
        {{ ckeditor_plugin(plugin_name, plugin) }}
    {% endfor %}
[...]
```

**sonata-project/formatter-bundle/Form/Type/FormatterType.php**
Add the PluginManagerInterface to the constructor arguments and pass plugins to the view.
```php
[...]
    /**
     * @var PluginManagerInterface
     */
    protected $pluginManager;

[...]
    /**
     * Constructor.
     *
     * @param Pool $pool A Formatter Pool service
     * @param TranslatorInterface $translator A Symfony Translator service
     * @param ConfigManagerInterface $configManager An Ivory CKEditor bundle configuration manager
     * @param PluginManagerInterface $pluginManager
     */
    public function __construct(Pool $pool, TranslatorInterface $translator, ConfigManagerInterface $configManager, PluginManagerInterface $pluginManager)
    {
        $this->pool = $pool;
        $this->translator = $translator;
        $this->configManager = $configManager;
        $this->pluginManager = $pluginManager;
    }
[...]
        // buildView() method:
        $view->vars['ckeditor_plugins'] = $this->pluginManager->getPlugins();
[...]
```

### PR DESCRIPTION
**Pull request by lisectech**
I am targetting this branch, because it fixes a bug that prevents loading CKEditor plugins from different sources.

Closes #196 
Fixes #196 

## Changelog

```markdown
### Added
- Added support for `PluginManagerInterface` in `FormatterType` and `SimpleFormatterType`
```

## Subject

Fixes CKEditor plugins loading in the RichHTML widget.

### CODE REVIEW

File: Form/Type/FormatterType.php [hunk 1]
```diff
@@ -41,17 +42,24 @@ class FormatterType extends AbstractType
...
+    /**
      * Constructor.
      *
      * @param Pool                   $pool          A Formatter Pool service
      * @param TranslatorInterface    $translator    A Symfony Translator service
      * @param ConfigManagerInterface $configManager An Ivory CKEditor bundle configuration manager
+     * @param PluginManagerInterface $pluginManager An Ivory CKEditor bundle plugin manager
      */
-    public function __construct(Pool $pool, TranslatorInterface $translator, ConfigManagerInterface $configManager)
+    public function __construct(Pool $pool, TranslatorInterface $translator, ConfigManagerInterface $configManager, PluginManagerInterface $pluginManager)
```
Comment (Soullivaneuh) [inline Form/Type/FormatterType.php]: Changing method signature is BC break.

File: Form/Type/SimpleFormatterType.php [hunk 2]
```diff
@@ -26,13 +27,20 @@ class SimpleFormatterType extends AbstractType
...
+    protected $pluginManager;
+
+    /**
      * Constructor.
      *
      * @param ConfigManagerInterface $configManager An Ivory CKEditor bundle configuration manager
+     * @param PluginManagerInterface $pluginManager An Ivory CKEditor bundle plugin manager
      */
-    public function __construct(ConfigManagerInterface $configManager)
+    public function __construct(ConfigManagerInterface $configManager, PluginManagerInterface $pluginManager)
```
Comment (Soullivaneuh) [inline Form/Type/SimpleFormatterType.php]: Changing method signature is BC break.

File: Tests/Form/Type/FormatterTypeTest.php [hunk 3]
```diff
@@ -27,8 +27,9 @@ public function testBuildFormOneChoice()
 
         $translator = $this->getMock('Symfony\Component\Translation\TranslatorInterface');
         $configManager = $this->getMock('Ivory\CKEditorBundle\Model\ConfigManagerInterface');
+        $pluginManager = $this->getMock('Ivory\CKEditorBundle\Model\PluginManagerInterface');
 
-        $type = new FormatterType($pool, $translator, $configManager);
+        $type = new FormatterType($pool, $translator, $configManager, $pluginManager);
```
Comment (Soullivaneuh) [inline Tests/Form/Type/FormatterTypeTest.php]: Previous test should not be changed. Both have to work.

File: Form/Type/FormatterType.php (hunk 1 above)
Comment (lisectech) [inline Form/Type/FormatterType.php]: Would you rather have me create and call setPluginManager() method or create PR into master?

Comment (core23) [inline Form/Type/FormatterType.php]: You could also supply a default value for the constructor to stay BC:
```php
    public function __construct(Pool $pool, TranslatorInterface $translator, ConfigManagerInterface $configManager, PluginManagerInterface $pluginManager = null) 
```

Comment (lisectech) [inline Form/Type/FormatterType.php]: You're right, I did not think of that. After the weekend I will update the constructors and tests.

File: Form/Type/FormatterType.php [hunk 4]
```diff
@@ -162,7 +162,7 @@ public function buildView(FormView $view, FormInterface $form, array $options)
             $ckeditorConfiguration = array_merge($ckeditorConfiguration, $contextConfig);
         }
 
-        if ($this->pluginManager->hasPlugins()) {
+        if ($this->pluginManager instanceof PluginManagerInterface && $this->pluginManager->hasPlugins()) {
             $options['ckeditor_plugins'] = $this->pluginManager->getPlugins();
```
Comment (core23) [inline Form/Type/FormatterType.php]: A simple null check would be better

File: Form/Type/FormatterType.php [hunk 5]
```diff
@@ -154,8 +162,13 @@ public function buildView(FormView $view, FormInterface $form, array $options)
             $ckeditorConfiguration = array_merge($ckeditorConfiguration, $contextConfig);
         }
 
+        if ($this->pluginManager !== null && $this->pluginManager->hasPlugins()) {
```
Comment (OskarStark) [inline Form/Type/FormatterType.php]:
```diff
- $this->pluginManager !== null
+ null !== $this->pluginManager
```

File: Form/Type/SimpleFormatterType.php [hunk 6]
```diff
@@ -49,8 +57,13 @@ public function buildView(FormView $view, FormInterface $form, array $options)
             $ckeditorConfiguration = array_merge($ckeditorConfiguration, $contextConfig);
         }
 
+        if ($this->pluginManager !== null && $this->pluginManager->hasPlugins()) {
```
Comment (OskarStark) [inline Form/Type/SimpleFormatterType.php]: same as above

**Comment by OskarStark** [comment]
LGTM 👍 

@Soullivaneuh the changelog looks a bit confusing IMO

File: Form/Type/FormatterType.php (hunk 5 above)
Comment (lisectech) [inline Form/Type/FormatterType.php]: Ok, I will fix this, I followed syntax from Twig/SecurityPolicyContainerAware.php:148 being aware of Yoda syntax ;)

Comment (OskarStark) [inline Form/Type/FormatterType.php]: 👍

File: Tests/Form/Type/FormatterTypeTest.php [hunk 7]
```diff
@@ -296,9 +343,43 @@ public function testBuildViewWithFormatter()
...
+
+        $defaultConfig = 'default';
+        $defaultConfigValues = array('toolbar' => array('Button1'));
+        $configManager->expects($this->once())->method('getDefaultConfig')->will($this->returnValue($defaultConfig));
+        $configManager->expects($this->once())->method('hasConfig')->with($defaultConfig)->will($this->returnValue(true));
+        $configManager->expects($this->once())->method('getConfig')->with($defaultConfig)->will($this->returnValue($defaultConfigValues));
+
+        $type = new FormatterType($pool, $translator, $configManager, $pluginManager);
+
+        /** @var \Symfony\Component\Form\FormView $view */
```
Comment (core23) [inline Tests/Form/Type/FormatterTypeTest.php]: Please don't use FQCN

Comment (lisectech) [inline Tests/Form/Type/FormatterTypeTest.php]: This is a copy of one of the previous tests with only $pluginManager added, so... I am a little bit confused. Could you explain, please?

Comment (OskarStark) [inline Tests/Form/Type/FormatterTypeTest.php]: please use this:

```diff
- /** @var \Symfony\Component\Form\FormView $view */
+ /** @var FormView $view */
```

and use use-stetement therefore.
Keep the old code as it is in this PR please. You can refactor this in a different PR.

Thank you

Comment (lisectech) [inline Tests/Form/Type/FormatterTypeTest.php]: Thank you for explaining this :)

**Comment by core23** [comment]
Updated the changelog message

**Comment by core23** [comment]
Thank you @lisectech
