### PR TITLE
Fixed initialisation in sf3+

### LINKED ISSUE #236: 'sonata_formatter_type' does not initially selects proper content format
See: [https://github.com/sonata-project/sandbox/issues/596](https://github.com/sonata-project/sandbox/issues/596)

## Text from issue:

Description: SonataNewsBundle uses 'sonata_formatter_type' for content field. When you save content with any other format, on edit, saved format is not selected.

Steps to reproduce a bug:

1. Go to sonata demo http://demo.sonata-project.org/ and create container, login into administration, go to dashboard (backend), path:  [domain]/admin/app/news-post/list
2. Open any news post for editing
3. Edit content by changing formatting type for field Content to, per  example "richhtml"
4. Click "Update" button

Expected result: Content is saved with new formatter, formatter is initially selected, CK editor is displayed on load.

Actual result: HTML code is displayed in Textarea, "markdown" content formatter is selected.

## Additional notes

I have tried to figure out where to search for issue, last thing what I have found is that `Sonata\FormatterBundle\Form\Type\FormatterType` does not provides a value for currently in-database saved formatter. I need help to figure this one out.

### PR DESCRIPTION
**Pull request by core23**
I am targeting this branch, because this is a bugfix.

Closes #236

## Changelog

```markdown
### Fixed
 - Fixed form initialisation in sf3+
```

## Subject

This should fix the init problem in symfony >=3.

### CODE REVIEW

**Comment by core23** [comment]
Can you please test this @TheCelavi

**Comment by TheCelavi** [comment]
@core23 Sorry, no, I do not maintain that project anymore where I have detected that bug.

Sorry and thanks!

File: src/Form/Type/FormatterType.php [hunk 1]
```diff
@@ -195,14 +195,19 @@ public function configureOptions(OptionsResolver $resolver)
...
+            $formatters[$translator->trans($code, [], 'SonataFormatterBundle')] = $code;
         }
 
         $formatFieldOptions = [
             'choices' => $formatters,
         ];
 
         if (count($formatters) > 1) {
+            // choice_as_value options is not needed in SF 3.0+
+            if (method_exists(FormTypeInterface::class, 'setDefaultOptions')) {
```
Comment (jordisala1991) [inline src/Form/Type/FormatterType.php]: Don't you need to add a use for this?

Comment (core23) [reply src/Form/Type/FormatterType.php]: Good catch!

File: src/Form/Type/FormatterType.php [hunk 2]
```diff
@@ -195,14 +196,19 @@ public function configureOptions(OptionsResolver $resolver)
...
-            $formatters[$code] = $translator->trans($code, [], 'SonataFormatterBundle');
+            $formatters[$translator->trans($code, [], 'SonataFormatterBundle')] = $code;
         }
 
         $formatFieldOptions = [
             'choices' => $formatters,
         ];
 
         if (count($formatters) > 1) {
+            // choice_as_value options is not needed in SF 3.0+
```
Comment (greg0ire) [inline src/Form/Type/FormatterType.php]: It's `choices_as_values`

File: src/Form/Type/FormatterType.php (hunk 1 above)
Comment (greg0ire) [reply src/Form/Type/FormatterType.php]: Why not use the `defined` trick here?

Comment (core23) [reply src/Form/Type/FormatterType.php]: Not sure if we can use this here. The `OptionsResolver` handles the options for `FormatterType`, not the options of `ChoiceType`

Comment (greg0ire) [reply src/Form/Type/FormatterType.php]: ok fair enough

File: src/Form/Type/FormatterType.php [hunk 3]
```diff
@@ -195,14 +196,19 @@ public function configureOptions(OptionsResolver $resolver)
...
-            $formatters[$code] = $translator->trans($code, [], 'SonataFormatterBundle');
+            $formatters[$translator->trans($code, [], 'SonataFormatterBundle')] = $code;
         }
 
         $formatFieldOptions = [
             'choices' => $formatters,
         ];
 
         if (count($formatters) > 1) {
+            // choice_as_values options is not needed in SF 3.0+
```
Comment (greg0ire) [inline src/Form/Type/FormatterType.php]: `choices` misses as "s" too

**Comment by core23** [comment]
Added a test

**Comment by jordisala1991** [comment]
You need to rebase @core23

**Comment by jordisala1991** [comment]
Please fix tests and we are ready to go @core23

**Comment by jordisala1991** [comment]
Nice coverage report, thank you @core23
